{
 "title": "WMTS metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "'wmts-1','wmts-2'" }
  ]
 },
 "panels": [
  {
   "title": "Production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response status codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "200s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent.hostname: wmts-*.hrvpp2.vgt.vito.be AND response:[200 TO 299]",
     "timeField": "@timestamp"
    },
    {
     "alias": "300s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent.hostname: wmts-*.hrvpp2.vgt.vito.be AND response:[300 TO 399]",
     "timeField": "@timestamp"
    },
    {
     "alias": "400s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent.hostname: wmts-*.hrvpp2.vgt.vito.be AND response:[400 TO 499]",
     "timeField": "@timestamp"
    },
    {
     "alias": "500s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent.hostname: wmts-*.hrvpp2.vgt.vito.be AND response:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average response time",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "agent.hostname: wmts-*.hrvpp2.vgt.vito.be",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Icinga check response times $host",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.${host}-viZoomLevel4__http__${host}_hrvpp2_vgt_vito_be.http.perfdata.time.value, 'VI zoom level 4')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.${host}-viZoomLevel9__http__${host}_hrvpp2_vgt_vito_be.http.perfdata.time.value, 'VI zoom level 9')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.${host}-vppZoomLevel4__http__${host}_hrvpp2_vgt_vito_be.http.perfdata.time.value, 'VPP zoom level 4')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.${host}-vppZoomLevel12__http__${host}_hrvpp2_vgt_vito_be.http.perfdata.time.value, 'VPP zoom level 12')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.${host}-stZoomLevel3__http__${host}_hrvpp2_vgt_vito_be.http.perfdata.time.value, 'ST zoom level 3')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.${host}-stZoomLevel11__http__${host}_hrvpp2_vgt_vito_be.http.perfdata.time.value, 'ST zoom level 11')"
    }
   ]
  },
  {
   "title": "Memory usage $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "repeat": "prod_host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.mem.mem.perfdata.USED.value, 'Used memory')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.mem.mem.perfdata.TOTAL.value, 'Total memory')"
    }
   ]
  },
  {
   "title": "Heap memory usage $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "repeat": "prod_host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-Memory-HeapMemoryUsage__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.max.value, 'Max Heap')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-Memory-HeapMemoryUsage__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.used.value, 'Heap used')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-Memory-NonHeapMemoryUsage__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.used.value, 'Non Heap used')"
    }
   ]
  },
  {
   "title": "Load $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "repeat": "prod_host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.$prod_host.services.load.load.perfdata.load1.value, 'Load 1')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.load.load.perfdata.load5.value, 'Load 5')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.load.load.perfdata.load15.value, 'Load 15')"
    }
   ]
  },
  {
   "title": "HTTPClient connections $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-SdkHttpClient-Available__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.SdkHttpClient.value, 'Available')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-SdkHttpClient-Leased__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.SdkHttpClient.value, 'Leased')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-SdkHttpClient-Pending__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.SdkHttpClient.value, 'Pending')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-SdkHttpClient-DefaultMaxPerRoute__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.SdkHttpClient.value, 'MaxPerRoute')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-SdkHttpClient-MaxTotal__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.SdkHttpClient.value, 'MaxTotal')"
    },
    {
     "target": "alias(icinga2.${host}_hrvpp2_vgt_vito_be.services.check_jmx-SdkHttpClient-RoutesTotal__check_jmx__${host}_hrvpp2_vgt_vito_be.check_jmx.perfdata.SdkHttpClient.value, 'RoutesTotal')"
    }
   ]
  }
 ]
}