{
 "title": "OSCARS OpenSearch metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Load oscars-1.hrvpp2.vgt.vito.be",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.oscars-1_hrvpp2_vgt_vito_be.services.load.load.perfdata.load1.value, 'load 1')"
    },
    {
     "target": "alias(icinga2.oscars-1_hrvpp2_vgt_vito_be.services.load.load.perfdata.load5.value, 'load 5')"
    },
    {
     "target": "alias(icinga2.oscars-1_hrvpp2_vgt_vito_be.services.load.load.perfdata.load15.value, 'load 15')"
    }
   ]
  },
  {
   "title": "Load oscars-2.hrvpp2.vgt.vito.be",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.oscars-2_hrvpp2_vgt_vito_be.services.load.load.perfdata.load1.value, 'load 1')"
    },
    {
     "target": "alias(icinga2.oscars-2_hrvpp2_vgt_vito_be.services.load.load.perfdata.load5.value, 'load 5')"
    },
    {
     "target": "alias(icinga2.oscars-2_hrvpp2_vgt_vito_be.services.load.load.perfdata.load15.value, 'load 15')"
    }
   ]
  },
  {
   "title": "Memory usage oscars-1.hrvpp2.vgt.vito.be",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.oscars-1_hrvpp2_vgt_vito_be.services.mem.mem.perfdata.USED.value, 'Used memory')"
    },
    {
     "target": "alias(icinga2.oscars-1_hrvpp2_vgt_vito_be.services.mem.mem.perfdata.TOTAL.value, 'Total memory')"
    }
   ]
  },
  {
   "title": "Memory usage oscars-2.hrvpp.vgt.vito.be",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.oscars-2_hrvpp2_vgt_vito_be.services.mem.mem.perfdata.USED.value, 'Used memory')"
    },
    {
     "target": "alias(icinga2.oscars-2_hrvpp2_vgt_vito_be.services.mem.mem.perfdata.TOTAL.value, 'Total memory')"
    }
   ]
  },
  {
   "title": "Response status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "200s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:oscars-?.hrvpp2.vgt.vito.be AND response:[200 TO 299]",
     "timeField": "@timestamp"
    },
    {
     "alias": "300s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:oscars-?.hrvpp2.vgt.vito.be AND response:[300 TO 399]",
     "timeField": "@timestamp"
    },
    {
     "alias": "400s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:oscars-?.hrvpp2.vgt.vito.be AND response:[400 TO 499]",
     "timeField": "@timestamp"
    },
    {
     "alias": "500s",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:oscars-?.hrvpp2.vgt.vito.be AND response:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Response time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "agent.hostname: oscars-?.hrvpp2.vgt.vito.be",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}