{
 "title": "Spark worker detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "spark_worker",
    "label": "Spark Worker",
    "query": "collectd.*-worker*_hrvpp2_vgt_vito_be"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$spark_worker.df-root.df_complex-used, 'used')"
    },
    {
     "target": "alias(collectd.$spark_worker.df-root.df_complex-free, 'free')"
    },
    {
     "target": "alias(collectd.$spark_worker.df-root.df_complex-reserved, 'reserved')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$spark_worker.memory.memory-free, 'free')"
    },
    {
     "target": "alias(collectd.$spark_worker.memory.memory-used, 'used')"
    },
    {
     "target": "alias(collectd.$spark_worker.memory.memory-cached, 'cache')"
    },
    {
     "target": "alias(sumSeries(collectd.$spark_worker.memory.memory-*), 'total')"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(collectd.$spark_worker.load.load.*)"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$spark_worker.interface-eth0.if_octets.rx, 'eth0 received')"
    },
    {
     "target": "alias(collectd.$spark_worker.interface-eth0.if_octets.tx, 'eth0 transmitted')"
    },
    {
     "target": "alias(collectd.$spark_worker.interface-eth1.if_octets.rx, 'eth1 received')"
    },
    {
     "target": "alias(collectd.$spark_worker.interface-eth1.if_octets.tx, 'eth1 transmitted')"
    }
   ]
  }
 ]
}