{
 "title": "Spark master detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Spark master",
    "query": "icinga2.*-master*_hrvpp2_vgt_vito_be"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.$host.services.disks.disk.perfdata._.value, 'used')"
    },
    {
     "target": "alias(icinga2.$host.services.disks.disk.perfdata._.max, 'max')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.$host.services.mem.mem.perfdata.FREE.value, 'free')"
    },
    {
     "target": "alias(icinga2.$host.services.mem.mem.perfdata.TOTAL.value, 'total')"
    },
    {
     "target": "alias(icinga2.$host.services.mem.mem.perfdata.USED.value, 'used')"
    },
    {
     "target": "alias(icinga2.$host.services.mem.mem.perfdata.CACHES.value, 'caches')"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.$host.services.load.load.perfdata.load1.value, 'load 1')"
    },
    {
     "target": "alias(icinga2.$host.services.load.load.perfdata.load5.value, 'load 5')"
    },
    {
     "target": "alias(icinga2.$host.services.load.load.perfdata.load15.value, 'load 15')"
    }
   ]
  }
 ]
}